
# Installs the configuration in the metastore
install:
	python config.py --install

# Uninstalls the configuration from the metastore
uninstall:
	python config.py --uninstall

# Cleans all configuration files
clean_config:
	rm -rf ./config.json
	rm -rf ./containers
