# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docker_stats_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64ocker_stats_manager.proto\".\n\x19StopDockerStatsMonitorMsg\x12\x11\n\temulation\x18\x01 \x01(\t\"\xa3\x01\n\x1aStartDockerStatsMonitorMsg\x12\x11\n\temulation\x18\x01 \x01(\t\x12\x0f\n\x07sink_ip\x18\x02 \x01(\t\x12\x1b\n\x13stats_queue_maxsize\x18\x03 \x01(\x05\x12\x1d\n\x15time_step_len_seconds\x18\x04 \x01(\x05\x12\x11\n\tsink_port\x18\x05 \x01(\x05\x12\x12\n\ncontainers\x18\x06 \x03(\t\" \n\x1eGetDockerStatsMonitorStatusMsg\"-\n\x15\x44ockerStatsMonitorDTO\x12\x14\n\x0cnum_monitors\x18\x01 \x01(\x05\x32\x90\x02\n\x12\x44ockerStatsManager\x12X\n\x1bgetDockerStatsMonitorStatus\x12\x1f.GetDockerStatsMonitorStatusMsg\x1a\x16.DockerStatsMonitorDTO\"\x00\x12N\n\x16stopDockerStatsMonitor\x12\x1a.StopDockerStatsMonitorMsg\x1a\x16.DockerStatsMonitorDTO\"\x00\x12P\n\x17startDockerStatsMonitor\x12\x1b.StartDockerStatsMonitorMsg\x1a\x16.DockerStatsMonitorDTO\"\x00\x62\x06proto3')



_STOPDOCKERSTATSMONITORMSG = DESCRIPTOR.message_types_by_name['StopDockerStatsMonitorMsg']
_STARTDOCKERSTATSMONITORMSG = DESCRIPTOR.message_types_by_name['StartDockerStatsMonitorMsg']
_GETDOCKERSTATSMONITORSTATUSMSG = DESCRIPTOR.message_types_by_name['GetDockerStatsMonitorStatusMsg']
_DOCKERSTATSMONITORDTO = DESCRIPTOR.message_types_by_name['DockerStatsMonitorDTO']
StopDockerStatsMonitorMsg = _reflection.GeneratedProtocolMessageType('StopDockerStatsMonitorMsg', (_message.Message,), {
  'DESCRIPTOR' : _STOPDOCKERSTATSMONITORMSG,
  '__module__' : 'docker_stats_manager_pb2'
  # @@protoc_insertion_point(class_scope:StopDockerStatsMonitorMsg)
  })
_sym_db.RegisterMessage(StopDockerStatsMonitorMsg)

StartDockerStatsMonitorMsg = _reflection.GeneratedProtocolMessageType('StartDockerStatsMonitorMsg', (_message.Message,), {
  'DESCRIPTOR' : _STARTDOCKERSTATSMONITORMSG,
  '__module__' : 'docker_stats_manager_pb2'
  # @@protoc_insertion_point(class_scope:StartDockerStatsMonitorMsg)
  })
_sym_db.RegisterMessage(StartDockerStatsMonitorMsg)

GetDockerStatsMonitorStatusMsg = _reflection.GeneratedProtocolMessageType('GetDockerStatsMonitorStatusMsg', (_message.Message,), {
  'DESCRIPTOR' : _GETDOCKERSTATSMONITORSTATUSMSG,
  '__module__' : 'docker_stats_manager_pb2'
  # @@protoc_insertion_point(class_scope:GetDockerStatsMonitorStatusMsg)
  })
_sym_db.RegisterMessage(GetDockerStatsMonitorStatusMsg)

DockerStatsMonitorDTO = _reflection.GeneratedProtocolMessageType('DockerStatsMonitorDTO', (_message.Message,), {
  'DESCRIPTOR' : _DOCKERSTATSMONITORDTO,
  '__module__' : 'docker_stats_manager_pb2'
  # @@protoc_insertion_point(class_scope:DockerStatsMonitorDTO)
  })
_sym_db.RegisterMessage(DockerStatsMonitorDTO)

_DOCKERSTATSMANAGER = DESCRIPTOR.services_by_name['DockerStatsManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOPDOCKERSTATSMONITORMSG._serialized_start=30
  _STOPDOCKERSTATSMONITORMSG._serialized_end=76
  _STARTDOCKERSTATSMONITORMSG._serialized_start=79
  _STARTDOCKERSTATSMONITORMSG._serialized_end=242
  _GETDOCKERSTATSMONITORSTATUSMSG._serialized_start=244
  _GETDOCKERSTATSMONITORSTATUSMSG._serialized_end=276
  _DOCKERSTATSMONITORDTO._serialized_start=278
  _DOCKERSTATSMONITORDTO._serialized_end=323
  _DOCKERSTATSMANAGER._serialized_start=326
  _DOCKERSTATSMANAGER._serialized_end=598
# @@protoc_insertion_point(module_scope)
