# Targets for running each individual env
run_level_1:
	cd 001/level_1/ && $(MAKE) run

run_level_2:
	cd 001/level_2/ && $(MAKE) run

run_level_3:
	cd 001/level_3/ && $(MAKE) run

run_level_4:
	cd 001/level_4/ && $(MAKE) run

run_level_5:
	cd 001/level_5/ && $(MAKE) run

run_level_6:
	cd 001/level_6/ && $(MAKE) run

run_level_7:
	cd 001/level_7/ && $(MAKE) run

run_level_8:
	cd 001/level_8/ && $(MAKE) run

run_level_9:
	cd 001/level_9/ && $(MAKE) run

run_level_10:
	cd 001/level_10/ && $(MAKE) run

run_level_11:
	cd 001/level_11/ && $(MAKE) run

run_level_13:
	cd 001/level_12/ && $(MAKE) run

# Runs all emulations (Warning: dont do this on a machine with limited resources!)
run:
	cd 001/level_1/ && $(MAKE) run
	cd 001/level_2/ && $(MAKE) run
	cd 001/level_3/ && $(MAKE) run
	cd 001/level_4/ && $(MAKE) run
	cd 001/level_5/ && $(MAKE) run
	cd 001/level_6/ && $(MAKE) run
	cd 001/level_7/ && $(MAKE) run
	cd 001/level_8/ && $(MAKE) run
	cd 001/level_9/ && $(MAKE) run
	cd 001/level_10/ && $(MAKE) run
	cd 001/level_11/ && $(MAKE) run
	cd 001/level_12/ && $(MAKE) run

# Targets for stopping each individual env
stop_level_1:
	cd 001/level_1/ && $(MAKE) stop

stop_level_2:
	cd 001/level_2/ && $(MAKE) stop

stop_level_3:
	cd 001/level_3/ && $(MAKE) stop

stop_level_4:
	cd 001/level_4/ && $(MAKE) stop

stop_level_5:
	cd 001/level_5/ && $(MAKE) stop

stop_level_6:
	cd 001/level_6/ && $(MAKE) stop

stop_level_7:
	cd 001/level_7/ && $(MAKE) stop

stop_level_8:
	cd 001/level_8/ && $(MAKE) stop

stop_level_9:
	cd 001/level_9/ && $(MAKE) stop

stop_level_10:
	cd 001/level_10/ && $(MAKE) stop

stop_level_11:
	cd 001/level_11/ && $(MAKE) stop

stop_level_12:
	cd 001/level_12/ && $(MAKE) stop

# Stops all emulations
stop:
	cd 001/level_1/ && $(MAKE) stop
	cd 001/level_2/ && $(MAKE) stop
	cd 001/level_3/ && $(MAKE) stop
	cd 001/level_4/ && $(MAKE) stop
	cd 001/level_5/ && $(MAKE) stop
	cd 001/level_6/ && $(MAKE) stop
	cd 001/level_7/ && $(MAKE) stop
	cd 001/level_8/ && $(MAKE) stop
	cd 001/level_9/ && $(MAKE) stop
	cd 001/level_10/ && $(MAKE) stop
	cd 001/level_11/ && $(MAKE) stop
	cd 001/level_12/ && $(MAKE) stop

# Targets for cleaning each individual env
clean_level_1:
	cd 001/level_1/ && $(MAKE) clean

clean_level_2:
	cd 001/level_2/ && $(MAKE) clean

clean_level_3:
	cd 001/level_3/ && $(MAKE) clean

clean_level_4:
	cd 001/level_4/ && $(MAKE) clean

clean_level_5:
	cd 001/level_5/ && $(MAKE) clean

clean_level_6:
	cd 001/level_6/ && $(MAKE) clean

clean_level_7:
	cd 001/level_7/ && $(MAKE) clean

clean_level_8:
	cd 001/level_8/ && $(MAKE) clean

clean_level_9:
	cd 001/level_9/ && $(MAKE) clean

clean_level_10:
	cd 001/level_10/ && $(MAKE) clean

clean_level_11:
	cd 001/level_11/ && $(MAKE) clean

clean_level_12:
	cd 001/level_12/ && $(MAKE) clean

# Cleans all emulations
clean:
	cd 001/level_1/ && $(MAKE) clean
	cd 001/level_2/ && $(MAKE) clean
	cd 001/level_3/ && $(MAKE) clean
	cd 001/level_4/ && $(MAKE) clean
	cd 001/level_5/ && $(MAKE) clean
	cd 001/level_6/ && $(MAKE) clean
	cd 001/level_7/ && $(MAKE) clean
	cd 001/level_8/ && $(MAKE) clean
	cd 001/level_9/ && $(MAKE) clean
	cd 001/level_10/ && $(MAKE) clean
	cd 001/level_11/ && $(MAKE) clean
	cd 001/level_12/ && $(MAKE) clean

# Targets for installing each individual env
install_level_1:
	cd 001/level_1/ && $(MAKE) install

install_level_2:
	cd 001/level_2/ && $(MAKE) install

install_level_3:
	cd 001/level_3/ && $(MAKE) install

install_level_4:
	cd 001/level_4/ && $(MAKE) install

install_level_5:
	cd 001/level_5/ && $(MAKE) install

install_level_6:
	cd 001/level_6/ && $(MAKE) install

install_level_7:
	cd 001/level_7/ && $(MAKE) install

install_level_8:
	cd 001/level_8/ && $(MAKE) install

install_level_9:
	cd 001/level_9/ && $(MAKE) install

install_level_10:
	cd 001/level_10/ && $(MAKE) install

install_level_11:
	cd 001/level_11/ && $(MAKE) install

install_level_12:
	cd 001/level_12/ && $(MAKE) install

# Installs all emulations
install:
	cd 001/level_1/ && $(MAKE) install
	cd 001/level_2/ && $(MAKE) install
	cd 001/level_3/ && $(MAKE) install
	cd 001/level_4/ && $(MAKE) install
	cd 001/level_5/ && $(MAKE) install
	cd 001/level_6/ && $(MAKE) install
	cd 001/level_7/ && $(MAKE) install
	cd 001/level_8/ && $(MAKE) install
	cd 001/level_9/ && $(MAKE) install
	cd 001/level_10/ && $(MAKE) install
	cd 001/level_11/ && $(MAKE) install
	cd 001/level_12/ && $(MAKE) install

# Targets for uninstalling each individual env
uninstall_level_1:
	cd 001/level_1/ && $(MAKE) uninstall

uninstall_level_2:
	cd 001/level_2/ && $(MAKE) uninstall

uninstall_level_3:
	cd 001/level_3/ && $(MAKE) uninstall

uninstall_level_4:
	cd 001/level_4/ && $(MAKE) uninstall

uninstall_level_5:
	cd 001/level_5/ && $(MAKE) uninstall

uninstall_level_6:
	cd 001/level_6/ && $(MAKE) uninstall

uninstall_level_7:
	cd 001/level_7/ && $(MAKE) uninstall

uninstall_level_8:
	cd 001/level_8/ && $(MAKE) uninstall

uninstall_level_9:
	cd 001/level_9/ && $(MAKE) uninstall

uninstall_level_10:
	cd 001/level_10/ && $(MAKE) uninstall

uninstall_level_11:
	cd 001/level_11/ && $(MAKE) uninstall

uninstall_level_12:
	cd 001/level_12/ && $(MAKE) uninstall

# Uninstalls all emulations
uninstall:
	cd 001/level_1/ && $(MAKE) uninstall
	cd 001/level_2/ && $(MAKE) uninstall
	cd 001/level_3/ && $(MAKE) uninstall
	cd 001/level_4/ && $(MAKE) uninstall
	cd 001/level_5/ && $(MAKE) uninstall
	cd 001/level_6/ && $(MAKE) uninstall
	cd 001/level_7/ && $(MAKE) uninstall
	cd 001/level_8/ && $(MAKE) uninstall
	cd 001/level_9/ && $(MAKE) uninstall
	cd 001/level_10/ && $(MAKE) uninstall
	cd 001/level_11/ && $(MAKE) uninstall
	cd 001/level_12/ && $(MAKE) uninstall

# Targets for cleaning the config each individual env
clean_config_level_1:
	cd 001/level_1/ && $(MAKE) clean_config

clean_config_level_2:
	cd 001/level_2/ && $(MAKE) clean_config

clean_config_level_3:
	cd 001/level_3/ && $(MAKE) clean_config

clean_config_level_4:
	cd 001/level_4/ && $(MAKE) clean_config

clean_config_level_5:
	cd 001/level_5/ && $(MAKE) clean_config

clean_config_level_6:
	cd 001/level_6/ && $(MAKE) clean_config

clean_config_level_7:
	cd 001/level_7/ && $(MAKE) clean_config

clean_config_level_8:
	cd 001/level_8/ && $(MAKE) clean_config

clean_config_level_9:
	cd 001/level_9/ && $(MAKE) clean_config

clean_config_level_10:
	cd 001/level_10/ && $(MAKE) clean_config

clean_config_level_11:
	cd 001/level_11/ && $(MAKE) clean_config

clean_config_level_12:
	cd 001/level_12/ && $(MAKE) clean_config

# Cleans the materialized configuration of each emulation
clean_config:
	cd 001/level_1/ && $(MAKE) clean_config
	cd 001/level_2/ && $(MAKE) clean_config
	cd 001/level_3/ && $(MAKE) clean_config
	cd 001/level_4/ && $(MAKE) clean_config
	cd 001/level_5/ && $(MAKE) clean_config
	cd 001/level_6/ && $(MAKE) clean_config
	cd 001/level_7/ && $(MAKE) clean_config
	cd 001/level_8/ && $(MAKE) clean_config
	cd 001/level_9/ && $(MAKE) clean_config
	cd 001/level_10/ && $(MAKE) clean_config
	cd 001/level_11/ && $(MAKE) clean_config
	cd 001/level_12/ && $(MAKE) clean_config

# Targets for applying the config of each individual env
apply_config_level_1:
	cd 001/level_1/ && $(MAKE) apply_config

apply_config_level_2:
	cd 001/level_2/ && $(MAKE) apply_config

apply_config_level_3:
	cd 001/level_3/ && $(MAKE) apply_config

apply_config_level_4:
	cd 001/level_4/ && $(MAKE) apply_config

apply_config_level_5:
	cd 001/level_5/ && $(MAKE) apply_config

apply_config_level_6:
	cd 001/level_6/ && $(MAKE) apply_config

apply_config_level_7:
	cd 001/level_7/ && $(MAKE) apply_config

apply_config_level_8:
	cd 001/level_8/ && $(MAKE) apply_config

apply_config_level_9:
	cd 001/level_9/ && $(MAKE) apply_config

apply_config_level_10:
	cd 001/level_10/ && $(MAKE) apply_config

apply_config_level_11:
	cd 001/level_11/ && $(MAKE) apply_config

apply_config_level_12:
	cd 001/level_12/ && $(MAKE) apply_config

# Applies the configuration to each emulation
apply_config:
	cd 001/level_1/ && $(MAKE) apply_config
	cd 001/level_2/ && $(MAKE) apply_config
	cd 001/level_3/ && $(MAKE) apply_config
	cd 001/level_4/ && $(MAKE) apply_config
	cd 001/level_5/ && $(MAKE) apply_config
	cd 001/level_6/ && $(MAKE) apply_config
	cd 001/level_7/ && $(MAKE) apply_config
	cd 001/level_8/ && $(MAKE) apply_config
	cd 001/level_9/ && $(MAKE) apply_config
	cd 001/level_10/ && $(MAKE) apply_config
	cd 001/level_11/ && $(MAKE) apply_config
	cd 001/level_12/ && $(MAKE) apply_config
