
# Runs all emulations (Warning: dont do this on a machine with limited resources!)
run:
	cd ctf/001/level_1/ && $(MAKE) run
	cd ctf/001/level_2/ && $(MAKE) run
	cd ctf/001/level_3/ && $(MAKE) run
	cd ctf/001/level_4/ && $(MAKE) run
	cd ctf/001/level_5/ && $(MAKE) run
	cd ctf/001/level_6/ && $(MAKE) run
	cd ctf/001/level_7/ && $(MAKE) run
	cd ctf/001/level_8/ && $(MAKE) run
	cd ctf/001/level_9/ && $(MAKE) run
	cd ctf/001/level_10/ && $(MAKE) run

# Stops all emulations
stop:
	cd ctf/001/level_1/ && $(MAKE) stop
	cd ctf/001/level_2/ && $(MAKE) stop
	cd ctf/001/level_3/ && $(MAKE) stop
	cd ctf/001/level_4/ && $(MAKE) stop
	cd ctf/001/level_5/ && $(MAKE) stop
	cd ctf/001/level_6/ && $(MAKE) stop
	cd ctf/001/level_7/ && $(MAKE) stop
	cd ctf/001/level_8/ && $(MAKE) stop
	cd ctf/001/level_9/ && $(MAKE) stop
	cd ctf/001/level_10/ && $(MAKE) stop

# Cleans all emulations
clean:
	cd ctf/001/level_1/ && $(MAKE) clean
	cd ctf/001/level_2/ && $(MAKE) clean
	cd ctf/001/level_3/ && $(MAKE) clean
	cd ctf/001/level_4/ && $(MAKE) clean
	cd ctf/001/level_5/ && $(MAKE) clean
	cd ctf/001/level_6/ && $(MAKE) clean
	cd ctf/001/level_7/ && $(MAKE) clean
	cd ctf/001/level_8/ && $(MAKE) clean
	cd ctf/001/level_9/ && $(MAKE) clean
	cd ctf/001/level_10/ && $(MAKE) clean

# Installs all emulations
install:
	cd ctf/001/level_1/ && $(MAKE) install
	cd ctf/001/level_2/ && $(MAKE) install
	cd ctf/001/level_3/ && $(MAKE) install
	cd ctf/001/level_4/ && $(MAKE) install
	cd ctf/001/level_5/ && $(MAKE) install
	cd ctf/001/level_6/ && $(MAKE) install
	cd ctf/001/level_7/ && $(MAKE) install
	cd ctf/001/level_8/ && $(MAKE) install
	cd ctf/001/level_9/ && $(MAKE) install
	cd ctf/001/level_10/ && $(MAKE) install

# Uninstalls all emulations
uninstall:
	cd ctf/001/level_1/ && $(MAKE) uninstall
	cd ctf/001/level_2/ && $(MAKE) uninstall
	cd ctf/001/level_3/ && $(MAKE) uninstall
	cd ctf/001/level_4/ && $(MAKE) uninstall
	cd ctf/001/level_5/ && $(MAKE) uninstall
	cd ctf/001/level_6/ && $(MAKE) uninstall
	cd ctf/001/level_7/ && $(MAKE) uninstall
	cd ctf/001/level_8/ && $(MAKE) uninstall
	cd ctf/001/level_9/ && $(MAKE) uninstall
	cd ctf/001/level_10/ && $(MAKE) uninstall

# Cleans the materialized configuration of each emulation
clean_config:
	cd ctf/001/level_1/ && $(MAKE) clean_config
	cd ctf/001/level_2/ && $(MAKE) clean_config
	cd ctf/001/level_3/ && $(MAKE) clean_config
	cd ctf/001/level_4/ && $(MAKE) clean_config
	cd ctf/001/level_5/ && $(MAKE) clean_config
	cd ctf/001/level_6/ && $(MAKE) clean_config
	cd ctf/001/level_7/ && $(MAKE) clean_config
	cd ctf/001/level_8/ && $(MAKE) clean_config
	cd ctf/001/level_9/ && $(MAKE) clean_config
	cd ctf/001/level_10/ && $(MAKE) clean_config

# Applies the configuration to each emulation
apply_config:
	cd ctf/001/level_1/ && $(MAKE) apply_config
	cd ctf/001/level_2/ && $(MAKE) apply_config
	cd ctf/001/level_3/ && $(MAKE) apply_config
	cd ctf/001/level_4/ && $(MAKE) apply_config
	cd ctf/001/level_5/ && $(MAKE) apply_config
	cd ctf/001/level_6/ && $(MAKE) apply_config
	cd ctf/001/level_7/ && $(MAKE) apply_config
	cd ctf/001/level_8/ && $(MAKE) apply_config
	cd ctf/001/level_9/ && $(MAKE) apply_config
	cd ctf/001/level_10/ && $(MAKE) apply_config