# Targets for installing each individual env
install_level_1:
	cd 070/level_1/ && $(MAKE) install

install_level_2:
	cd 070/level_2/ && $(MAKE) install

install_level_3:
	cd 070/level_3/ && $(MAKE) install

install_level_4:
	cd 070/level_4/ && $(MAKE) install

install_level_5:
	cd 070/level_5/ && $(MAKE) install

install_level_6:
	cd 070/level_6/ && $(MAKE) install

install_level_7:
	cd 070/level_7/ && $(MAKE) install

install_level_8:
	cd 070/level_8/ && $(MAKE) install

install_level_9:
	cd 070/level_9/ && $(MAKE) install

install_level_10:
	cd 070/level_10/ && $(MAKE) install

install_level_11:
	cd 070/level_11/ && $(MAKE) install

install_level_12:
	cd 070/level_12/ && $(MAKE) install

install_level_13:
	cd 070/level_13/ && $(MAKE) install

install_level_14:
	cd 070/level_14/ && $(MAKE) install

install_level_15:
	cd 070/level_15/ && $(MAKE) install

# Installs all emulations
install:
	cd 070/level_1/ && $(MAKE) install
	cd 070/level_2/ && $(MAKE) install
	cd 070/level_3/ && $(MAKE) install
	cd 070/level_4/ && $(MAKE) install
	cd 070/level_5/ && $(MAKE) install
	cd 070/level_6/ && $(MAKE) install
	cd 070/level_7/ && $(MAKE) install
	cd 070/level_8/ && $(MAKE) install
	cd 070/level_9/ && $(MAKE) install
	cd 070/level_10/ && $(MAKE) install
	cd 070/level_11/ && $(MAKE) install
	cd 070/level_12/ && $(MAKE) install
	cd 070/level_13/ && $(MAKE) install
	cd 070/level_14/ && $(MAKE) install
	cd 070/level_15/ && $(MAKE) install

# Targets for uninstalling each individual env
uninstall_level_1:
	cd 070/level_1/ && $(MAKE) uninstall

uninstall_level_2:
	cd 070/level_2/ && $(MAKE) uninstall

uninstall_level_3:
	cd 070/level_3/ && $(MAKE) uninstall

uninstall_level_4:
	cd 070/level_4/ && $(MAKE) uninstall

uninstall_level_5:
	cd 070/level_5/ && $(MAKE) uninstall

uninstall_level_6:
	cd 070/level_6/ && $(MAKE) uninstall

uninstall_level_7:
	cd 070/level_7/ && $(MAKE) uninstall

uninstall_level_8:
	cd 070/level_8/ && $(MAKE) uninstall

uninstall_level_9:
	cd 070/level_9/ && $(MAKE) uninstall

uninstall_level_10:
	cd 070/level_10/ && $(MAKE) uninstall

uninstall_level_11:
	cd 070/level_11/ && $(MAKE) uninstall

uninstall_level_12:
	cd 070/level_12/ && $(MAKE) uninstall

uninstall_level_13:
	cd 070/level_13/ && $(MAKE) uninstall

uninstall_level_14:
	cd 070/level_14/ && $(MAKE) uninstall

uninstall_level_15:
	cd 070/level_15/ && $(MAKE) uninstall

# Uninstalls all emulations
uninstall:
	cd 070/level_1/ && $(MAKE) uninstall
	cd 070/level_2/ && $(MAKE) uninstall
	cd 070/level_3/ && $(MAKE) uninstall
	cd 070/level_4/ && $(MAKE) uninstall
	cd 070/level_5/ && $(MAKE) uninstall
	cd 070/level_6/ && $(MAKE) uninstall
	cd 070/level_7/ && $(MAKE) uninstall
	cd 070/level_8/ && $(MAKE) uninstall
	cd 070/level_9/ && $(MAKE) uninstall
	cd 070/level_10/ && $(MAKE) uninstall
	cd 070/level_11/ && $(MAKE) uninstall
	cd 070/level_12/ && $(MAKE) uninstall
	cd 070/level_13/ && $(MAKE) uninstall
	cd 070/level_14/ && $(MAKE) uninstall
	cd 070/level_15/ && $(MAKE) uninstall

# Targets for cleaning the config each individual env
clean_config_level_1:
	cd 070/level_1/ && $(MAKE) clean_config

clean_config_level_2:
	cd 070/level_2/ && $(MAKE) clean_config

clean_config_level_3:
	cd 070/level_3/ && $(MAKE) clean_config

clean_config_level_4:
	cd 070/level_4/ && $(MAKE) clean_config

clean_config_level_5:
	cd 070/level_5/ && $(MAKE) clean_config

clean_config_level_6:
	cd 070/level_6/ && $(MAKE) clean_config

clean_config_level_7:
	cd 070/level_7/ && $(MAKE) clean_config

clean_config_level_8:
	cd 070/level_8/ && $(MAKE) clean_config

clean_config_level_9:
	cd 070/level_9/ && $(MAKE) clean_config

clean_config_level_10:
	cd 070/level_10/ && $(MAKE) clean_config

clean_config_level_11:
	cd 070/level_11/ && $(MAKE) clean_config

clean_config_level_12:
	cd 070/level_12/ && $(MAKE) clean_config

clean_config_level_13:
	cd 070/level_13/ && $(MAKE) clean_config

clean_config_level_14:
	cd 070/level_14/ && $(MAKE) clean_config

clean_config_level_15:
	cd 070/level_15/ && $(MAKE) clean_config

# Cleans the materialized configuration of each emulation
clean_config:
	cd 070/level_1/ && $(MAKE) clean_config
	cd 070/level_2/ && $(MAKE) clean_config
	cd 070/level_3/ && $(MAKE) clean_config
	cd 070/level_4/ && $(MAKE) clean_config
	cd 070/level_5/ && $(MAKE) clean_config
	cd 070/level_6/ && $(MAKE) clean_config
	cd 070/level_7/ && $(MAKE) clean_config
	cd 070/level_8/ && $(MAKE) clean_config
	cd 070/level_9/ && $(MAKE) clean_config
	cd 070/level_10/ && $(MAKE) clean_config
	cd 070/level_11/ && $(MAKE) clean_config
	cd 070/level_12/ && $(MAKE) clean_config
	cd 070/level_13/ && $(MAKE) clean_config
	cd 070/level_14/ && $(MAKE) clean_config
	cd 070/level_15/ && $(MAKE) clean_config
