const containersNameAndOs = {
  csle_ssh_1: [{
    name: 'csle_ssh_1',
    os: 'ubuntu'}],
  csle_router_2: [{
    name: 'csle_router_2',
    os: 'ubuntu'}],
  csle_samba_2: [{
    name: 'csle_samba_2',
    os: 'debian'}],
  csle_honeypot_1: [{
    name: 'csle_honeypot_1',
    os: 'ubuntu'}],
  csle_ftp_1: [{
    name: 'csle_ftp_1',
    os: 'ubuntu'}],
  csle_hacker_kali_1: [{
    name: 'csle_hacker_kali_1',
    os: 'kali'}],
  csle_shellshock_1: [{
    name: 'csle_shellshock_1',
    os: 'debian'}],
  csle_sql_injection_1: [{
    name: 'csle_sql_injection_1',
    os: 'debian'}],
  csle_cve_2010_0426_1: [{
    name: 'csle_cve_2010_0426_1',
    os: 'debian'}],
  csle_cve_2015_1427_1: [{
    name: 'csle_cve_2015_1427_1',
    os: 'debian'}],
  csle_honeypot_2: [{
    name: 'csle_honeypot_2',
    os: 'ubuntu'}],
  csle_cve_2015_3306_1: [{
    name: 'csle_cve_2015_3306_1',
    os: 'debian'}],
  csle_cve_2015_5602_1: [{
    name: 'csle_cve_2015_5602_1',
    os: 'debian'}],
  csle_cve_2016_10033_1: [{
    name: 'csle_cve_2016_10033_1',
    os: 'debian'}],
  csle_client_1: [{
    name: 'csle_client_1',
    os: 'ubuntu'}],
  csle_kafka_1: [{
    name: 'csle_kafka_1',
    os: 'ubuntu'}],
  csle_elk_1: [{
    name: 'csle_elk_1',
    os: 'ubuntu'}],
  csle_router_1: [{
    name: 'csle_router_1',
    os: 'ubuntu'}],
  csle_telnet_1: [{
    name: 'csle_telnet_1',
    os: 'ubuntu'}],
  csle_ssh_2: [{
    name: 'csle_ssh_2',
    os: 'ubuntu'}],
  csle_ssh_3: [{
    name: 'csle_ssh_3',
    os: 'ubuntu'}],
  csle_telnet_2: [{
    name: 'csle_telnet_2',
    os: 'ubuntu'}],
  csle_telnet_3: [{
    name: 'csle_telnet_3',
    os: 'ubuntu'}],
  csle_ftp_2: [{
    name: 'csle_ftp_2',
    os: 'ubuntu'}],
  csle_ovs_1: [{
    name: 'csle_ovs_1',
    os: 'ubuntu'}],
  csle_ryu_1: [{
    name: 'csle_ryu_1',
    os: 'ubuntu'}],
  csle_pengine_exploit_1: [{
    name: 'csle_pengine_exploit_1',
    os: 'ubuntu'}],
  csle_cve_2014_0160_1: [{
    name: 'csle_cve_2014_0160_1',
    os: 'debian'}],
  csle_spark_1: [{
    name: 'csle_spark_1',
    os: 'spark'}]
};

export default containersNameAndOs;
