# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import csle_cluster.cluster_manager.cluster_manager_pb2 as cluster__manager__pb2


class ClusterManagerStub(object):
    """Interface exported by the server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getNodeStatus = channel.unary_unary(
                '/ClusterManager/getNodeStatus',
                request_serializer=cluster__manager__pb2.GetNodeStatusMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.NodeStatusDTO.FromString,
                )
        self.startPostgreSQL = channel.unary_unary(
                '/ClusterManager/startPostgreSQL',
                request_serializer=cluster__manager__pb2.StartPostgreSQLMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startCAdvisor = channel.unary_unary(
                '/ClusterManager/startCAdvisor',
                request_serializer=cluster__manager__pb2.StartCAdvisorMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startNodeExporter = channel.unary_unary(
                '/ClusterManager/startNodeExporter',
                request_serializer=cluster__manager__pb2.StartNodeExporterMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startGrafana = channel.unary_unary(
                '/ClusterManager/startGrafana',
                request_serializer=cluster__manager__pb2.StartGrafanaMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startPrometheus = channel.unary_unary(
                '/ClusterManager/startPrometheus',
                request_serializer=cluster__manager__pb2.StartPrometheusMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startPgAdmin = channel.unary_unary(
                '/ClusterManager/startPgAdmin',
                request_serializer=cluster__manager__pb2.StartPgAdminMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startNginx = channel.unary_unary(
                '/ClusterManager/startNginx',
                request_serializer=cluster__manager__pb2.StartNginxMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startFlask = channel.unary_unary(
                '/ClusterManager/startFlask',
                request_serializer=cluster__manager__pb2.StartFlaskMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startDockerStatsManager = channel.unary_unary(
                '/ClusterManager/startDockerStatsManager',
                request_serializer=cluster__manager__pb2.StartDockerStatsManagerMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.startDockerEngine = channel.unary_unary(
                '/ClusterManager/startDockerEngine',
                request_serializer=cluster__manager__pb2.StartDockerEngineMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopPostgreSQL = channel.unary_unary(
                '/ClusterManager/stopPostgreSQL',
                request_serializer=cluster__manager__pb2.StopPostgreSQLMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopCAdvisor = channel.unary_unary(
                '/ClusterManager/stopCAdvisor',
                request_serializer=cluster__manager__pb2.StopCAdvisorMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopNodeExporter = channel.unary_unary(
                '/ClusterManager/stopNodeExporter',
                request_serializer=cluster__manager__pb2.StopNodeExporterMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopGrafana = channel.unary_unary(
                '/ClusterManager/stopGrafana',
                request_serializer=cluster__manager__pb2.StopGrafanaMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopPrometheus = channel.unary_unary(
                '/ClusterManager/stopPrometheus',
                request_serializer=cluster__manager__pb2.StopPrometheusMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopPgAdmin = channel.unary_unary(
                '/ClusterManager/stopPgAdmin',
                request_serializer=cluster__manager__pb2.StopPgAdminMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopNginx = channel.unary_unary(
                '/ClusterManager/stopNginx',
                request_serializer=cluster__manager__pb2.StopNginxMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopFlask = channel.unary_unary(
                '/ClusterManager/stopFlask',
                request_serializer=cluster__manager__pb2.StopFlaskMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopDockerStatsManager = channel.unary_unary(
                '/ClusterManager/stopDockerStatsManager',
                request_serializer=cluster__manager__pb2.StopDockerStatsManagerMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )
        self.stopDockerEngine = channel.unary_unary(
                '/ClusterManager/stopDockerEngine',
                request_serializer=cluster__manager__pb2.StopDockerEngineMsg.SerializeToString,
                response_deserializer=cluster__manager__pb2.ServiceStatusDTO.FromString,
                )


class ClusterManagerServicer(object):
    """Interface exported by the server
    """

    def getNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startPostgreSQL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startCAdvisor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startNodeExporter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startGrafana(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startPrometheus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startPgAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startNginx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startFlask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startDockerStatsManager(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startDockerEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopPostgreSQL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopCAdvisor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopNodeExporter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopGrafana(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopPrometheus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopPgAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopNginx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopFlask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopDockerStatsManager(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopDockerEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getNodeStatus,
                    request_deserializer=cluster__manager__pb2.GetNodeStatusMsg.FromString,
                    response_serializer=cluster__manager__pb2.NodeStatusDTO.SerializeToString,
            ),
            'startPostgreSQL': grpc.unary_unary_rpc_method_handler(
                    servicer.startPostgreSQL,
                    request_deserializer=cluster__manager__pb2.StartPostgreSQLMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startCAdvisor': grpc.unary_unary_rpc_method_handler(
                    servicer.startCAdvisor,
                    request_deserializer=cluster__manager__pb2.StartCAdvisorMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startNodeExporter': grpc.unary_unary_rpc_method_handler(
                    servicer.startNodeExporter,
                    request_deserializer=cluster__manager__pb2.StartNodeExporterMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startGrafana': grpc.unary_unary_rpc_method_handler(
                    servicer.startGrafana,
                    request_deserializer=cluster__manager__pb2.StartGrafanaMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startPrometheus': grpc.unary_unary_rpc_method_handler(
                    servicer.startPrometheus,
                    request_deserializer=cluster__manager__pb2.StartPrometheusMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startPgAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.startPgAdmin,
                    request_deserializer=cluster__manager__pb2.StartPgAdminMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startNginx': grpc.unary_unary_rpc_method_handler(
                    servicer.startNginx,
                    request_deserializer=cluster__manager__pb2.StartNginxMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startFlask': grpc.unary_unary_rpc_method_handler(
                    servicer.startFlask,
                    request_deserializer=cluster__manager__pb2.StartFlaskMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startDockerStatsManager': grpc.unary_unary_rpc_method_handler(
                    servicer.startDockerStatsManager,
                    request_deserializer=cluster__manager__pb2.StartDockerStatsManagerMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'startDockerEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.startDockerEngine,
                    request_deserializer=cluster__manager__pb2.StartDockerEngineMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopPostgreSQL': grpc.unary_unary_rpc_method_handler(
                    servicer.stopPostgreSQL,
                    request_deserializer=cluster__manager__pb2.StopPostgreSQLMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopCAdvisor': grpc.unary_unary_rpc_method_handler(
                    servicer.stopCAdvisor,
                    request_deserializer=cluster__manager__pb2.StopCAdvisorMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopNodeExporter': grpc.unary_unary_rpc_method_handler(
                    servicer.stopNodeExporter,
                    request_deserializer=cluster__manager__pb2.StopNodeExporterMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopGrafana': grpc.unary_unary_rpc_method_handler(
                    servicer.stopGrafana,
                    request_deserializer=cluster__manager__pb2.StopGrafanaMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopPrometheus': grpc.unary_unary_rpc_method_handler(
                    servicer.stopPrometheus,
                    request_deserializer=cluster__manager__pb2.StopPrometheusMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopPgAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.stopPgAdmin,
                    request_deserializer=cluster__manager__pb2.StopPgAdminMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopNginx': grpc.unary_unary_rpc_method_handler(
                    servicer.stopNginx,
                    request_deserializer=cluster__manager__pb2.StopNginxMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopFlask': grpc.unary_unary_rpc_method_handler(
                    servicer.stopFlask,
                    request_deserializer=cluster__manager__pb2.StopFlaskMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopDockerStatsManager': grpc.unary_unary_rpc_method_handler(
                    servicer.stopDockerStatsManager,
                    request_deserializer=cluster__manager__pb2.StopDockerStatsManagerMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
            'stopDockerEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.stopDockerEngine,
                    request_deserializer=cluster__manager__pb2.StopDockerEngineMsg.FromString,
                    response_serializer=cluster__manager__pb2.ServiceStatusDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClusterManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClusterManager(object):
    """Interface exported by the server
    """

    @staticmethod
    def getNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/getNodeStatus',
            cluster__manager__pb2.GetNodeStatusMsg.SerializeToString,
            cluster__manager__pb2.NodeStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startPostgreSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startPostgreSQL',
            cluster__manager__pb2.StartPostgreSQLMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startCAdvisor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startCAdvisor',
            cluster__manager__pb2.StartCAdvisorMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startNodeExporter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startNodeExporter',
            cluster__manager__pb2.StartNodeExporterMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startGrafana(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startGrafana',
            cluster__manager__pb2.StartGrafanaMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startPrometheus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startPrometheus',
            cluster__manager__pb2.StartPrometheusMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startPgAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startPgAdmin',
            cluster__manager__pb2.StartPgAdminMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startNginx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startNginx',
            cluster__manager__pb2.StartNginxMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startFlask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startFlask',
            cluster__manager__pb2.StartFlaskMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startDockerStatsManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startDockerStatsManager',
            cluster__manager__pb2.StartDockerStatsManagerMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startDockerEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/startDockerEngine',
            cluster__manager__pb2.StartDockerEngineMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopPostgreSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopPostgreSQL',
            cluster__manager__pb2.StopPostgreSQLMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopCAdvisor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopCAdvisor',
            cluster__manager__pb2.StopCAdvisorMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopNodeExporter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopNodeExporter',
            cluster__manager__pb2.StopNodeExporterMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopGrafana(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopGrafana',
            cluster__manager__pb2.StopGrafanaMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopPrometheus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopPrometheus',
            cluster__manager__pb2.StopPrometheusMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopPgAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopPgAdmin',
            cluster__manager__pb2.StopPgAdminMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopNginx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopNginx',
            cluster__manager__pb2.StopNginxMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopFlask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopFlask',
            cluster__manager__pb2.StopFlaskMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopDockerStatsManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopDockerStatsManager',
            cluster__manager__pb2.StopDockerStatsManagerMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopDockerEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClusterManager/stopDockerEngine',
            cluster__manager__pb2.StopDockerEngineMsg.SerializeToString,
            cluster__manager__pb2.ServiceStatusDTO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
