# Targets for installing each individual env
install_stopping_game:
	cd stopping_game/ && $(MAKE) install

install_stopping_mdp_attacker:
	cd stopping_mdp_attacker/ && $(MAKE) install

install_stopping_pomdp_defender:
	cd stopping_pomdp_defender/ && $(MAKE) install

install_local_intrusion_response_pomdp_defender:
	cd local_intrusion_response_pomdp_defender/ && $(MAKE) install

install_local_intrusion_response_pomdp_attacker:
	cd local_intrusion_response_pomdp_attacker/ && $(MAKE) install

install_workflow_intrusion_response_pomdp_attacker:
	cd workflow_intrusion_response_pomdp_attacker/ && $(MAKE) install

install_workflow_intrusion_response_pomdp_defender:
	cd workflow_intrusion_response_pomdp_defender/ && $(MAKE) install

install_intrusion_recovery_pomdp_defender:
	cd intrusion_recovery_pomdp_defender/ && $(MAKE) install

install_intrusion_response_cmdp_defender:
	cd intrusion_response_cmdp_defender/ && $(MAKE) install

install_apt_game:
	cd apt_game/ && $(MAKE) install

install_apt_mdp_attacker:
	cd apt_mdp_attacker/ && $(MAKE) install

install_apt_pomdp_defender:
	cd apt_pomdp_defender/ && $(MAKE) install

install_cyborg:
	cd cyborg/ && $(MAKE) install

# Installs all simulations
install:
	cd stopping_game/ && $(MAKE) install
	cd stopping_mdp_attacker/ && $(MAKE) install
	cd stopping_pomdp_defender/ && $(MAKE) install
	cd local_intrusion_response_pomdp_attacker/ && $(MAKE) install
	cd local_intrusion_response_pomdp_defender/ && $(MAKE) install
	cd workflow_intrusion_response_pomdp_attacker/ && $(MAKE) install
	cd workflow_intrusion_response_pomdp_defender/ && $(MAKE) install
	cd intrusion_recovery_pomdp_defender/ && $(MAKE) install
	cd intrusion_response_cmdp_defender/ && $(MAKE) install
	cd apt_game/ && $(MAKE) install
	cd apt_mdp_attacker/ && $(MAKE) install
	cd apt_pomdp_defender/ && $(MAKE) install
	cd cyborg/ && $(MAKE) install

# Targets for uninstalling each individual env
uninstall_stopping_game:
	cd stopping_game/ && $(MAKE) uninstall

uninstall_stopping_mdp_attacker:
	cd stopping_mdp_attacker/ && $(MAKE) uninstall

uninstall_stopping_pomdp_defender:
	cd stopping_pomdp_defender/ && $(MAKE) uninstall

uninstall_local_intrusion_response_pomdp_defender:
	cd local_intrusion_response_pomdp_defender/ && $(MAKE) uninstall

uninstall_local_intrusion_response_pomdp_attacker:
	cd local_intrusion_response_pomdp_attacker/ && $(MAKE) uninstall

uninstall_workflow_intrusion_response_pomdp_attacker:
	cd workflow_intrusion_response_pomdp_attacker/ && $(MAKE) uninstall

uninstall_workflow_intrusion_response_pomdp_defender:
	cd workflow_intrusion_response_pomdp_defender/ && $(MAKE) uninstall

uninstall_intrusion_recovery_pomdp_defender:
	cd intrusion_recovery_pomdp_defender/ && $(MAKE) uninstall

uninstall_intrusion_response_cmdp_defender:
	cd intrusion_response_cmdp_defender/ && $(MAKE) uninstall

uninstall_apt_game:
	cd apt_game/ && $(MAKE) uninstall

uninstall_apt_mdp_attacker:
	cd apt_mdp_attacker/ && $(MAKE) uninstall

uninstall_apt_pomdp_defender:
	cd apt_pomdp_defender/ && $(MAKE) uninstall

uninstall_cyborg:
	cd cyborg/ && $(MAKE) uninstall

# Uninstalls all simulation envs
uninstall:
	cd stopping_game/ && $(MAKE) uninstall
	cd stopping_mdp_attacker/ && $(MAKE) uninstall
	cd stopping_pomdp_defender/ && $(MAKE) uninstall
	cd local_intrusion_response_pomdp_attacker/ && $(MAKE) uninstall
	cd local_intrusion_response_pomdp_defender/ && $(MAKE) uninstall
	cd workflow_intrusion_response_pomdp_attacker/ && $(MAKE) uninstall
	cd workflow_intrusion_response_pomdp_defender/ && $(MAKE) uninstall
	cd intrusion_recovery_pomdp_defender/ && $(MAKE) uninstall
	cd intrusion_response_cmdp_defender/ && $(MAKE) uninstall
	cd apt_game/ && $(MAKE) uninstall
	cd apt_mdp_attacker/ && $(MAKE) uninstall
	cd apt_pomdp_defender/ && $(MAKE) uninstall
	cd cyborg/ && $(MAKE) uninstall

# Targets for cleaning the config each individual env
clean_config_stopping_game:
	cd stopping_game/ && $(MAKE) clean_config

clean_config_stopping_mdp_attacker:
	cd stopping_mdp_attacker/ && $(MAKE) clean_config

clean_config_stopping_pomdp_defender:
	cd stopping_pomdp_defender/ && $(MAKE) clean_config

clean_local_intrusion_response_pomdp_defender:
	cd local_intrusion_response_pomdp_defender/ && $(MAKE) clean

clean_local_intrusion_response_pomdp_attacker:
	cd local_intrusion_response_pomdp_attacker/ && $(MAKE) clean

clean_workflow_intrusion_response_pomdp_attacker:
	cd workflow_intrusion_response_pomdp_attacker/ && $(MAKE) clean

clean_workflow_intrusion_response_pomdp_defender:
	cd workflow_intrusion_response_pomdp_defender/ && $(MAKE) clean

clean_intrusion_recovery_pomdp_defender:
	cd intrusion_recovery_pomdp_defender/ && $(MAKE) clean

clean_intrusion_response_cmdp_defender:
	cd intrusion_response_cmdp_defender/ && $(MAKE) clean

clean_config_apt_game:
	cd apt_game/ && $(MAKE) clean_config

clean_config_apt_mdp_attacker:
	cd apt_mdp_attacker/ && $(MAKE) clean_config

clean_config_apt_pomdp_defender:
	cd apt_pomdp_defender/ && $(MAKE) clean_config

cyborg:
	cd cyborg/ && $(MAKE) clean_config

# Cleans the materialized configuration of each emulation
clean_config:
	cd stopping_game/ && $(MAKE) clean_config
	cd stopping_mdp_attacker/ && $(MAKE) clean_config
	cd stopping_pomdp_defender/ && $(MAKE) clean_config
	cd local_intrusion_response_pomdp_attacker/ && $(MAKE) clean_config
	cd local_intrusion_response_pomdp_defender/ && $(MAKE) clean_config
	cd workflow_intrusion_response_pomdp_attacker/ && $(MAKE) clean_config
	cd workflow_intrusion_response_pomdp_defender/ && $(MAKE) clean_config
	cd intrusion_recovery_pomdp_defender/ && $(MAKE) clean_config
	cd intrusion_response_cmdp_defender/ && $(MAKE) clean_config
	cd apt_game/ && $(MAKE) clean_config
	cd apt_mdp_attacker/ && $(MAKE) clean_config
	cd apt_pomdp_defender/ && $(MAKE) clean_config
	cd cyborg/ && $(MAKE) clean_config
