all: run users topology vuln gen_containers_config flags traffic

.PHONY: run

run:
	cd containers/blank1/ && $(MAKE) run

stop:
	cd containers/blank1/ && $(MAKE) stop

start:
	cd containers/blank1/ && $(MAKE) start

clean:
	cd containers/blank1/ && $(MAKE) clean
