all: build

build:
	cd ftp1/ && $(MAKE) build
	cd ftp2/ && $(MAKE) build
	cd hacker_kali1/ && $(MAKE) build
	cd honeypot1/ && $(MAKE) build
	cd honeypot2/ && $(MAKE) build
	cd ssh1/ && $(MAKE) build
	cd ssh2/ && $(MAKE) build
	cd ssh3/ && $(MAKE) build
	cd telnet1/ && $(MAKE) build
	cd telnet2/ && $(MAKE) build
	cd telnet3/ && $(MAKE) build
	cd router1/ && $(MAKE) build
	cd router2/ && $(MAKE) build
	cd samba1/ && $(MAKE) build
	cd shellshock1/ && $(MAKE) build
	cd sql_injection1/ && $(MAKE) build

rm-image:
	cd ftp1/ && $(MAKE) rm-image
	cd ftp2/ && $(MAKE) rm-image
	cd hacker_kali1/ && $(MAKE) rm-image
	cd honeypot1/ && $(MAKE) rm-image
	cd honeypot2/ && $(MAKE) rm-image
	cd ssh1/ && $(MAKE) rm-image
	cd ssh2/ && $(MAKE) rm-image
	cd ssh3/ && $(MAKE) rm-image
	cd telnet1/ && $(MAKE) rm-image
	cd telnet2/ && $(MAKE) rm-image
	cd telnet3/ && $(MAKE) rm-image
	cd router1/ && $(MAKE) rm-image
	cd router2/ && $(MAKE) rm-image
	cd samba1/ && $(MAKE) rm-image
	cd shellshock1/ && $(MAKE) rm-image
	cd sql_injection1/ && $(MAKE) rm-image