---

- hosts: all
  become: true

  vars:
    user: "shahab"

  tasks:

  - name: Check if Conda environment py39 exists
    shell: "/home/{{ user }}/anaconda3/bin/conda env list"
    register: conda_env_list
    changed_when: false

  - name: Check if py39 environment is in the list
    set_fact:
      py39_env_exists: "{{ 'py39' in conda_env_list.stdout }}" 

  - name: Create and activate py39 environment if it does not exist
    shell: |
      "/home/{{ user }}/anaconda3/bin/conda" create -y -n py39 python=3.9 && \
      source "/home/{{ user }}/anaconda3/bin/activate" py39 && \
      "/home/{{ user }}/anaconda3/bin/conda" install -y pip
    args:
      executable: /bin/bash
    when: not py39_env_exists

  - name: Activate the environment if it exist and install csle-base
    shell: |
      source "/home/{{ user }}/anaconda3/bin/activate" py39
      "/home/{{ user }}/anaconda3/envs/py39/bin/pip" install csle-base
#    when: py39_env_exists

  - name: Activate the environment if it exist and install csle-collector
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-collector"
#    when: py39_env_exists 

  - name: Activate the environment if it exist and install csle-ryu
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-ryu"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-common
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-common"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-attacker
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-attacker"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-defender
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-defender"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-system-identification
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-system-identification"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install gym-csle-stopping-game
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install gym-csle-stopping-game"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install gym-csle-apt-game
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install gym-csle-apt-game"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install gym-csle-cyborg
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install gym-csle-cyborg"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-agents
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-agents"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-rest-api
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-rest-api"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-cli
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-cli"
#    when: py39_env_exists
     
  - name: Activate the environment if it existi and install csle-cluster
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-cluster"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install gym-csle-intrusion-response-game
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install gym-csle-intrusion-response-game"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and install csle-tolerance
    shell: "/home/{{ user }}/anaconda3/envs/py39/bin/pip install csle-tolerance"
#    when: py39_env_exists
     
  - name: Activate the environment if it exist and run last command on the leader node
    shell: |
      source "/home/{{ user }}/anaconda3/bin/activate" py39 && \
      cd "/home/{{ user }}/csle/simulation-system/envs" && \
      make install
    args:
      executable: /bin/bash
#    when: py39_env_exists
