---

- hosts: all

  tasks:

    - name: Start postgres
      become: true
      service:
        name: postgresql
        state: started

    - name: Change permissions on start script
      become: true
      command: sudo chmod -R u+rwx "/home/{{ user }}/csle/ansible/start.sh"

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Execute start script on the leader node
      command: "python /home/{{ user }}/csle/ansible/start_services.py {{ leader_ip }} {{ user }} {{ conda_environment_name }}"

    - name: Execute start scripts on the worker nodes
      command: "python /home/{{ user }}/csle/ansible/start_services.py {{ item }} {{ user }} {{ conda_environment_name }}"
      loop: "{{ groups['worker'] }}"