all: build

build:
	cd ftp_1/ && $(MAKE) build
	cd ftp_2/ && $(MAKE) build
	cd hacker_kali_1/ && $(MAKE) build
	cd honeypot_1/ && $(MAKE) build
	cd honeypot_2/ && $(MAKE) build
	cd ssh_1/ && $(MAKE) build
	cd ssh_2/ && $(MAKE) build
	cd ssh_3/ && $(MAKE) build
	cd telnet_1/ && $(MAKE) build
	cd telnet_2/ && $(MAKE) build
	cd telnet_3/ && $(MAKE) build
	cd router_1/ && $(MAKE) build
	cd router_2/ && $(MAKE) build
	cd samba_1/ && $(MAKE) build
	cd samba_2/ && $(MAKE) build
	cd shellshock_1/ && $(MAKE) build
	cd sql_injection_1/ && $(MAKE) build
	cd cve_2015_3306_1/ && $(MAKE) build
	cd cve_2015_1427_1/ && $(MAKE) build
	cd cve_2016_10033_1/ && $(MAKE) build
	cd cve_2010_0426_1/ && $(MAKE) build
	cd cve_2015_5602_1/ && $(MAKE) build
	cd client_1/ && $(MAKE) build
	cd blank_1/ && $(MAKE) build
	cd pengine_exploit_1/ && $(MAKE) build

rm-image:
	cd ftp_1/ && $(MAKE) rm-image
	cd ftp_2/ && $(MAKE) rm-image
	cd hacker_kali_1/ && $(MAKE) rm-image
	cd honeypot_1/ && $(MAKE) rm-image
	cd honeypot_2/ && $(MAKE) rm-image
	cd ssh_1/ && $(MAKE) rm-image
	cd ssh_2/ && $(MAKE) rm-image
	cd ssh_3/ && $(MAKE) rm-image
	cd telnet_1/ && $(MAKE) rm-image
	cd telnet_2/ && $(MAKE) rm-image
	cd telnet_3/ && $(MAKE) rm-image
	cd router_1/ && $(MAKE) rm-image
	cd router_2/ && $(MAKE) rm-image
	cd samba_1/ && $(MAKE) rm-image
	cd samba_2/ && $(MAKE) rm-image
	cd shellshock_1/ && $(MAKE) rm-image
	cd sql_injection_1/ && $(MAKE) rm-image
	cd cve_2015_3306_1/ && $(MAKE) rm-image
	cd cve_2015_1427_1/ && $(MAKE) rm-image
	cd cve_2016_10033_1/ && $(MAKE) rm-image
	cd cve_2010_0426_1/ && $(MAKE) rm-image
	cd cve_2015_5602_1/ && $(MAKE) rm-image
	cd client_1/ && $(MAKE) rm-image
	cd blank_1/ && $(MAKE) rm-image
	cd pengine_exploit_1/ && $(MAKE) rm-image